<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Kabupaten;

class KabupatenSeeder extends Seeder
{
    public function run(): void
    {
        $kabupaten = [
            // NAD ACEH (1)
            ['kode' => '1', 'nama' => 'KABUPATEN ACEH BARAT', 'provinsi_kode' => '1'],
            ['kode' => '2', 'nama' => 'KABUPATEN ACEH BARAT DAYA', 'provinsi_kode' => '1'],
            ['kode' => '3', 'nama' => 'KABUPATEN ACEH BESAR', 'provinsi_kode' => '1'],
            ['kode' => '4', 'nama' => 'KABUPATEN ACEH JAYA', 'provinsi_kode' => '1'],
            ['kode' => '5', 'nama' => 'KABUPATEN ACEH SELATAN', 'provinsi_kode' => '1'],
            ['kode' => '6', 'nama' => 'KABUPATEN ACEH SINGKIL', 'provinsi_kode' => '1'],
            ['kode' => '7', 'nama' => 'KABUPATEN ACEH TAMIANG', 'provinsi_kode' => '1'],
            ['kode' => '8', 'nama' => 'KABUPATEN ACEH TENGAH', 'provinsi_kode' => '1'],
            ['kode' => '9', 'nama' => 'KABUPATEN ACEH TENGGARA', 'provinsi_kode' => '1'],
            ['kode' => '10', 'nama' => 'KABUPATEN ACEH TIMUR', 'provinsi_kode' => '1'],
            ['kode' => '11', 'nama' => 'KABUPATEN ACEH UTARA', 'provinsi_kode' => '1'],
            ['kode' => '12', 'nama' => 'KABUPATEN BENER MERIAH', 'provinsi_kode' => '1'],
            ['kode' => '13', 'nama' => 'KABUPATEN BIREUEN', 'provinsi_kode' => '1'],
            ['kode' => '14', 'nama' => 'KABUPATEN GAYO LUES', 'provinsi_kode' => '1'],
            ['kode' => '15', 'nama' => 'KABUPATEN NAGAN RAYA', 'provinsi_kode' => '1'],
            ['kode' => '16', 'nama' => 'KABUPATEN PIDIE', 'provinsi_kode' => '1'],
            ['kode' => '17', 'nama' => 'KABUPATEN PIDIE JAYA', 'provinsi_kode' => '1'],
            ['kode' => '18', 'nama' => 'KABUPATEN SIMEULUE', 'provinsi_kode' => '1'],
            ['kode' => '19', 'nama' => 'KOTA BANDA ACEH', 'provinsi_kode' => '1'],
            ['kode' => '20', 'nama' => 'KOTA LANGSA', 'provinsi_kode' => '1'],
            ['kode' => '21', 'nama' => 'KOTA LHOKSEUMAWE', 'provinsi_kode' => '1'],
            ['kode' => '22', 'nama' => 'KOTA SABANG', 'provinsi_kode' => '1'],
            ['kode' => '23', 'nama' => 'KOTA SUBULUSSALAM', 'provinsi_kode' => '1'],

            // SUMATERA UTARA (2)
            ['kode' => '24', 'nama' => 'KABUPATEN ASAHAN', 'provinsi_kode' => '2'],
            ['kode' => '25', 'nama' => 'KABUPATEN BATUBARA', 'provinsi_kode' => '2'],
            ['kode' => '26', 'nama' => 'KABUPATEN DAIRI', 'provinsi_kode' => '2'],
            ['kode' => '27', 'nama' => 'KABUPATEN DELI SERDANG', 'provinsi_kode' => '2'],
            ['kode' => '28', 'nama' => 'KABUPATEN HUMBANG HASUNDUTAN', 'provinsi_kode' => '2'],
            ['kode' => '29', 'nama' => 'KABUPATEN KARO', 'provinsi_kode' => '2'],
            ['kode' => '30', 'nama' => 'KABUPATEN LABUHANBATU', 'provinsi_kode' => '2'],
            ['kode' => '31', 'nama' => 'KABUPATEN LABUHANBATU SELATAN', 'provinsi_kode' => '2'],
            ['kode' => '32', 'nama' => 'KABUPATEN LABUHANBATU UTARA', 'provinsi_kode' => '2'],
            ['kode' => '33', 'nama' => 'KABUPATEN LANGKAT', 'provinsi_kode' => '2'],
            ['kode' => '34', 'nama' => 'KABUPATEN MANDAILING NATAL', 'provinsi_kode' => '2'],
            ['kode' => '35', 'nama' => 'KABUPATEN NIAS', 'provinsi_kode' => '2'],
            ['kode' => '36', 'nama' => 'KABUPATEN NIAS BARAT', 'provinsi_kode' => '2'],
            ['kode' => '37', 'nama' => 'KABUPATEN NIAS SELATAN', 'provinsi_kode' => '2'],
            ['kode' => '38', 'nama' => 'KABUPATEN NIAS UTARA', 'provinsi_kode' => '2'],
            ['kode' => '39', 'nama' => 'KABUPATEN PADANG LAWAS', 'provinsi_kode' => '2'],
            ['kode' => '40', 'nama' => 'KABUPATEN PADANG LAWAS UTARA', 'provinsi_kode' => '2'],
            ['kode' => '41', 'nama' => 'KABUPATEN PAKPAK BHARAT', 'provinsi_kode' => '2'],
            ['kode' => '42', 'nama' => 'KABUPATEN SAMOSIR', 'provinsi_kode' => '2'],
            ['kode' => '43', 'nama' => 'KABUPATEN SERDANG BEDAGAI', 'provinsi_kode' => '2'],
            ['kode' => '44', 'nama' => 'KABUPATEN SIMALUNGUN', 'provinsi_kode' => '2'],
            ['kode' => '45', 'nama' => 'KABUPATEN TAPANULI SELATAN', 'provinsi_kode' => '2'],
            ['kode' => '46', 'nama' => 'KABUPATEN TAPANULI TENGAH', 'provinsi_kode' => '2'],
            ['kode' => '47', 'nama' => 'KABUPATEN TAPANULI UTARA', 'provinsi_kode' => '2'],
            ['kode' => '48', 'nama' => 'KABUPATEN TOBA SAMOSIR', 'provinsi_kode' => '2'],
            ['kode' => '49', 'nama' => 'KOTA BINJAI', 'provinsi_kode' => '2'],
            ['kode' => '50', 'nama' => 'KOTA GUNUNGSITOLI', 'provinsi_kode' => '2'],
            ['kode' => '51', 'nama' => 'KOTA MEDAN', 'provinsi_kode' => '2'],
            ['kode' => '52', 'nama' => 'KOTA PADANGSIDEMPUAN', 'provinsi_kode' => '2'],
            ['kode' => '53', 'nama' => 'KOTA PEMATANGSIANTAR', 'provinsi_kode' => '2'],
            ['kode' => '54', 'nama' => 'KOTA SIBOLGA', 'provinsi_kode' => '2'],
            ['kode' => '55', 'nama' => 'KOTA TANJUNGBALAI', 'provinsi_kode' => '2'],
            ['kode' => '56', 'nama' => 'KOTA TEBING TINGGI', 'provinsi_kode' => '2'],

            // SUMATERA BARAT (3)
            ['kode' => '57', 'nama' => 'KABUPATEN AGAM', 'provinsi_kode' => '3'],
            ['kode' => '58', 'nama' => 'KABUPATEN DHARMASRAYA', 'provinsi_kode' => '3'],
            ['kode' => '59', 'nama' => 'KABUPATEN KEPULAUAN MENTAWAI', 'provinsi_kode' => '3'],
            ['kode' => '60', 'nama' => 'KABUPATEN LIMA PULUH KOTA', 'provinsi_kode' => '3'],
            ['kode' => '61', 'nama' => 'KABUPATEN PADANG PARIAMAN', 'provinsi_kode' => '3'],
            ['kode' => '62', 'nama' => 'KABUPATEN PASAMAN', 'provinsi_kode' => '3'],
            ['kode' => '63', 'nama' => 'KABUPATEN PASAMAN BARAT', 'provinsi_kode' => '3'],
            ['kode' => '64', 'nama' => 'KABUPATEN PESISIR SELATAN', 'provinsi_kode' => '3'],
            ['kode' => '65', 'nama' => 'KABUPATEN SIJUNJUNG', 'provinsi_kode' => '3'],
            ['kode' => '66', 'nama' => 'KABUPATEN SOLOK', 'provinsi_kode' => '3'],
            ['kode' => '67', 'nama' => 'KABUPATEN SOLOK SELATAN', 'provinsi_kode' => '3'],
            ['kode' => '68', 'nama' => 'KABUPATEN TANAH DATAR', 'provinsi_kode' => '3'],
            ['kode' => '69', 'nama' => 'KOTA BUKITTINGGI', 'provinsi_kode' => '3'],
            ['kode' => '70', 'nama' => 'KOTA PADANG', 'provinsi_kode' => '3'],
            ['kode' => '71', 'nama' => 'KOTA PADANGPANJANG', 'provinsi_kode' => '3'],
            ['kode' => '72', 'nama' => 'KOTA PARIAMAN', 'provinsi_kode' => '3'],
            ['kode' => '73', 'nama' => 'KOTA PAYAKUMBUH', 'provinsi_kode' => '3'],
            ['kode' => '74', 'nama' => 'KOTA SAWAHLUNTO', 'provinsi_kode' => '3'],
            ['kode' => '75', 'nama' => 'KOTA SOLOK', 'provinsi_kode' => '3'],

            // SUMATERA SELATAN (4)
            ['kode' => '76', 'nama' => 'KABUPATEN BANYUASIN', 'provinsi_kode' => '4'],
            ['kode' => '77', 'nama' => 'KABUPATEN EMPAT LAWANG', 'provinsi_kode' => '4'],
            ['kode' => '78', 'nama' => 'KABUPATEN LAHAT', 'provinsi_kode' => '4'],
            ['kode' => '79', 'nama' => 'KABUPATEN MUARA ENIM', 'provinsi_kode' => '4'],
            ['kode' => '80', 'nama' => 'KABUPATEN MUSI BANYUASIN', 'provinsi_kode' => '4'],
            ['kode' => '81', 'nama' => 'KABUPATEN MUSI RAWAS', 'provinsi_kode' => '4'],
            ['kode' => '82', 'nama' => 'KABUPATEN MUSI RAWAS UTARA', 'provinsi_kode' => '4'],
            ['kode' => '83', 'nama' => 'KABUPATEN OGAN ILIR', 'provinsi_kode' => '4'],
            ['kode' => '84', 'nama' => 'KABUPATEN OGAN KOMERING ILIR', 'provinsi_kode' => '4'],
            ['kode' => '85', 'nama' => 'KABUPATEN OGAN KOMERING ULU', 'provinsi_kode' => '4'],
            ['kode' => '86', 'nama' => 'KABUPATEN OGAN KOMERING ULU SELATAN', 'provinsi_kode' => '4'],
            ['kode' => '87', 'nama' => 'KABUPATEN OGAN KOMERING ULU TIMUR', 'provinsi_kode' => '4'],
            ['kode' => '88', 'nama' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'provinsi_kode' => '4'],
            ['kode' => '89', 'nama' => 'KOTA LUBUKLINGGAU', 'provinsi_kode' => '4'],
            ['kode' => '90', 'nama' => 'KOTA PAGAR ALAM', 'provinsi_kode' => '4'],
            ['kode' => '91', 'nama' => 'KOTA PALEMBANG', 'provinsi_kode' => '4'],
            ['kode' => '92', 'nama' => 'KOTA PRABUMULIH', 'provinsi_kode' => '4'],

            // RIAU (5)
            ['kode' => '93', 'nama' => 'KABUPATEN BENGKALIS', 'provinsi_kode' => '5'],
            ['kode' => '94', 'nama' => 'KABUPATEN INDRAGIRI HILIR', 'provinsi_kode' => '5'],
            ['kode' => '95', 'nama' => 'KABUPATEN INDRAGIRI HULU', 'provinsi_kode' => '5'],
            ['kode' => '96', 'nama' => 'KABUPATEN KAMPAR', 'provinsi_kode' => '5'],
            ['kode' => '97', 'nama' => 'KABUPATEN KEPULAUAN MERANTI', 'provinsi_kode' => '5'],
            ['kode' => '98', 'nama' => 'KABUPATEN KUANTAN SINGINGI', 'provinsi_kode' => '5'],
            ['kode' => '99', 'nama' => 'KABUPATEN PELALAWAN', 'provinsi_kode' => '5'],
            ['kode' => '100', 'nama' => 'KABUPATEN ROKAN HILIR', 'provinsi_kode' => '5'],
            ['kode' => '101', 'nama' => 'KABUPATEN ROKAN HULU', 'provinsi_kode' => '5'],
            ['kode' => '102', 'nama' => 'KABUPATEN SIAK', 'provinsi_kode' => '5'],
            ['kode' => '103', 'nama' => 'KOTA DUMAI', 'provinsi_kode' => '5'],
            ['kode' => '104', 'nama' => 'KOTA PEKANBARU', 'provinsi_kode' => '5'],

            // KEPULAUAN RIAU (6)
            ['kode' => '105', 'nama' => 'KABUPATEN BINTAN', 'provinsi_kode' => '6'],
            ['kode' => '106', 'nama' => 'KABUPATEN KARIMUN', 'provinsi_kode' => '6'],
            ['kode' => '107', 'nama' => 'KABUPATEN KEPULAUAN ANAMBAS', 'provinsi_kode' => '6'],
            ['kode' => '108', 'nama' => 'KABUPATEN LINGGA', 'provinsi_kode' => '6'],
            ['kode' => '109', 'nama' => 'KABUPATEN NATUNA', 'provinsi_kode' => '6'],
            ['kode' => '110', 'nama' => 'KOTA BATAM', 'provinsi_kode' => '6'],
            ['kode' => '111', 'nama' => 'KOTA TANJUNG PINANG', 'provinsi_kode' => '6'],

            // JAMBI (7)
            ['kode' => '112', 'nama' => 'KABUPATEN BATANGHARI', 'provinsi_kode' => '7'],
            ['kode' => '113', 'nama' => 'KABUPATEN BUNGO', 'provinsi_kode' => '7'],
            ['kode' => '114', 'nama' => 'KABUPATEN KERINCI', 'provinsi_kode' => '7'],
            ['kode' => '115', 'nama' => 'KABUPATEN MERANGIN', 'provinsi_kode' => '7'],
            ['kode' => '116', 'nama' => 'KABUPATEN MUARO JAMBI', 'provinsi_kode' => '7'],
            ['kode' => '117', 'nama' => 'KABUPATEN SAROLANGUN', 'provinsi_kode' => '7'],
            ['kode' => '118', 'nama' => 'KABUPATEN TANJUNG JABUNG BARAT', 'provinsi_kode' => '7'],
            ['kode' => '119', 'nama' => 'KABUPATEN TANJUNG JABUNG TIMUR', 'provinsi_kode' => '7'],
            ['kode' => '120', 'nama' => 'KABUPATEN TEBO', 'provinsi_kode' => '7'],
            ['kode' => '121', 'nama' => 'KOTA JAMBI', 'provinsi_kode' => '7'],
            ['kode' => '122', 'nama' => 'KOTA SUNGAI PENUH', 'provinsi_kode' => '7'],

            // BENGKULU (8)
            ['kode' => '123', 'nama' => 'KABUPATEN BENGKULU SELATAN', 'provinsi_kode' => '8'],
            ['kode' => '124', 'nama' => 'KABUPATEN BENGKULU TENGAH', 'provinsi_kode' => '8'],
            ['kode' => '125', 'nama' => 'KABUPATEN BENGKULU UTARA', 'provinsi_kode' => '8'],
            ['kode' => '126', 'nama' => 'KABUPATEN KAUR', 'provinsi_kode' => '8'],
            ['kode' => '127', 'nama' => 'KABUPATEN KEPAHIANG', 'provinsi_kode' => '8'],
            ['kode' => '128', 'nama' => 'KABUPATEN LEBONG', 'provinsi_kode' => '8'],
            ['kode' => '129', 'nama' => 'KABUPATEN MUKOMUKO', 'provinsi_kode' => '8'],
            ['kode' => '130', 'nama' => 'KABUPATEN REJANG LEBONG', 'provinsi_kode' => '8'],
            ['kode' => '131', 'nama' => 'KABUPATEN SELUMA', 'provinsi_kode' => '8'],
            ['kode' => '132', 'nama' => 'KOTA BENGKULU', 'provinsi_kode' => '8'],

            // BANGKA BELITUNG (9)
            ['kode' => '133', 'nama' => 'KABUPATEN BANGKA', 'provinsi_kode' => '9'],
            ['kode' => '134', 'nama' => 'KABUPATEN BANGKA BARAT', 'provinsi_kode' => '9'],
            ['kode' => '135', 'nama' => 'KABUPATEN BANGKA SELATAN', 'provinsi_kode' => '9'],
            ['kode' => '136', 'nama' => 'KABUPATEN BANGKA TENGAH', 'provinsi_kode' => '9'],
            ['kode' => '137', 'nama' => 'KABUPATEN BELITUNG', 'provinsi_kode' => '9'],
            ['kode' => '138', 'nama' => 'KABUPATEN BELITUNG TIMUR', 'provinsi_kode' => '9'],
            ['kode' => '139', 'nama' => 'KOTA PANGKAL PINANG', 'provinsi_kode' => '9'],

            // LAMPUNG (10)
            ['kode' => '140', 'nama' => 'KABUPATEN LAMPUNG TENGAH', 'provinsi_kode' => '10'],
            ['kode' => '141', 'nama' => 'KABUPATEN LAMPUNG UTARA', 'provinsi_kode' => '10'],
            ['kode' => '142', 'nama' => 'KABUPATEN LAMPUNG SELATAN', 'provinsi_kode' => '10'],
            ['kode' => '143', 'nama' => 'KABUPATEN LAMPUNG BARAT', 'provinsi_kode' => '10'],
            ['kode' => '144', 'nama' => 'KABUPATEN LAMPUNG TIMUR', 'provinsi_kode' => '10'],
            ['kode' => '145', 'nama' => 'KABUPATEN MESUJI', 'provinsi_kode' => '10'],
            ['kode' => '146', 'nama' => 'KABUPATEN PESAWARAN', 'provinsi_kode' => '10'],
            ['kode' => '147', 'nama' => 'KABUPATEN PESISIR BARAT', 'provinsi_kode' => '10'],
            ['kode' => '148', 'nama' => 'KABUPATEN PRINGSEWU', 'provinsi_kode' => '10'],
            ['kode' => '149', 'nama' => 'KABUPATEN TULANG BAWANG', 'provinsi_kode' => '10'],
            ['kode' => '150', 'nama' => 'KABUPATEN TULANG BAWANG BARAT', 'provinsi_kode' => '10'],
            ['kode' => '151', 'nama' => 'KABUPATEN TANGGAMUS', 'provinsi_kode' => '10'],
            ['kode' => '152', 'nama' => 'KABUPATEN WAY KANAN', 'provinsi_kode' => '10'],
            ['kode' => '153', 'nama' => 'KOTA BANDAR LAMPUNG', 'provinsi_kode' => '10'],
            ['kode' => '154', 'nama' => 'KOTA METRO', 'provinsi_kode' => '10'],

            // BANTEN (11)
            ['kode' => '155', 'nama' => 'KABUPATEN LEBAK', 'provinsi_kode' => '11'],
            ['kode' => '156', 'nama' => 'KABUPATEN PANDEGLANG', 'provinsi_kode' => '11'],
            ['kode' => '157', 'nama' => 'KABUPATEN SERANG', 'provinsi_kode' => '11'],
            ['kode' => '158', 'nama' => 'KABUPATEN TANGERANG', 'provinsi_kode' => '11'],
            ['kode' => '159', 'nama' => 'KOTA CILEGON', 'provinsi_kode' => '11'],
            ['kode' => '160', 'nama' => 'KOTA SERANG', 'provinsi_kode' => '11'],
            ['kode' => '161', 'nama' => 'KOTA TANGERANG', 'provinsi_kode' => '11'],
            ['kode' => '162', 'nama' => 'KOTA TANGERANG SELATAN', 'provinsi_kode' => '11'],

            // JAWA BARAT (12)
            ['kode' => '163', 'nama' => 'KABUPATEN BANDUNG', 'provinsi_kode' => '12'],
            ['kode' => '164', 'nama' => 'KABUPATEN BANDUNG BARAT', 'provinsi_kode' => '12'],
            ['kode' => '165', 'nama' => 'KABUPATEN BEKASI', 'provinsi_kode' => '12'],
            ['kode' => '166', 'nama' => 'KABUPATEN BOGOR', 'provinsi_kode' => '12'],
            ['kode' => '167', 'nama' => 'KABUPATEN CIAMIS', 'provinsi_kode' => '12'],
            ['kode' => '168', 'nama' => 'KABUPATEN CIANJUR', 'provinsi_kode' => '12'],
            ['kode' => '169', 'nama' => 'KABUPATEN CIREBON', 'provinsi_kode' => '12'],
            ['kode' => '170', 'nama' => 'KABUPATEN GARUT', 'provinsi_kode' => '12'],
            ['kode' => '171', 'nama' => 'KABUPATEN INDRAMAYU', 'provinsi_kode' => '12'],
            ['kode' => '172', 'nama' => 'KABUPATEN KARAWANG', 'provinsi_kode' => '12'],
            ['kode' => '173', 'nama' => 'KABUPATEN KUNINGAN', 'provinsi_kode' => '12'],
            ['kode' => '174', 'nama' => 'KABUPATEN MAJALENGKA', 'provinsi_kode' => '12'],
            ['kode' => '175', 'nama' => 'KABUPATEN PANGANDARAN', 'provinsi_kode' => '12'],
            ['kode' => '176', 'nama' => 'KABUPATEN PURWAKARTA', 'provinsi_kode' => '12'],
            ['kode' => '177', 'nama' => 'KABUPATEN SUBANG', 'provinsi_kode' => '12'],
            ['kode' => '178', 'nama' => 'KABUPATEN SUKABUMI', 'provinsi_kode' => '12'],
            ['kode' => '179', 'nama' => 'KABUPATEN SUMEDANG', 'provinsi_kode' => '12'],
            ['kode' => '180', 'nama' => 'KABUPATEN TASIKMALAYA', 'provinsi_kode' => '12'],
            ['kode' => '181', 'nama' => 'KOTA BANDUNG', 'provinsi_kode' => '12'],
            ['kode' => '182', 'nama' => 'KOTA BANJAR', 'provinsi_kode' => '12'],
            ['kode' => '183', 'nama' => 'KOTA BEKASI', 'provinsi_kode' => '12'],
            ['kode' => '184', 'nama' => 'KOTA BOGOR', 'provinsi_kode' => '12'],
            ['kode' => '185', 'nama' => 'KOTA CIMAHI', 'provinsi_kode' => '12'],
            ['kode' => '186', 'nama' => 'KOTA CIREBON', 'provinsi_kode' => '12'],
            ['kode' => '187', 'nama' => 'KOTA DEPOK', 'provinsi_kode' => '12'],
            ['kode' => '188', 'nama' => 'KOTA SUKABUMI', 'provinsi_kode' => '12'],
            ['kode' => '189', 'nama' => 'KOTA TASIKMALAYA', 'provinsi_kode' => '12'],

            // JAWA TENGAH (13)
            ['kode' => '190', 'nama' => 'KABUPATEN BANJARNEGARA', 'provinsi_kode' => '13'],
            ['kode' => '191', 'nama' => 'KABUPATEN BANYUMAS', 'provinsi_kode' => '13'],
            ['kode' => '192', 'nama' => 'KABUPATEN BATANG', 'provinsi_kode' => '13'],
            ['kode' => '193', 'nama' => 'KABUPATEN BLORA', 'provinsi_kode' => '13'],
            ['kode' => '194', 'nama' => 'KABUPATEN BOYOLALI', 'provinsi_kode' => '13'],
            ['kode' => '195', 'nama' => 'KABUPATEN BREBES', 'provinsi_kode' => '13'],
            ['kode' => '196', 'nama' => 'KABUPATEN CILACAP', 'provinsi_kode' => '13'],
            ['kode' => '197', 'nama' => 'KABUPATEN DEMAK', 'provinsi_kode' => '13'],
            ['kode' => '198', 'nama' => 'KABUPATEN GROBOGAN', 'provinsi_kode' => '13'],
            ['kode' => '199', 'nama' => 'KABUPATEN JEPARA', 'provinsi_kode' => '13'],
            ['kode' => '200', 'nama' => 'KABUPATEN KARANGANYAR', 'provinsi_kode' => '13'],
            ['kode' => '201', 'nama' => 'KABUPATEN KEBUMEN', 'provinsi_kode' => '13'],
            ['kode' => '202', 'nama' => 'KABUPATEN KENDAL', 'provinsi_kode' => '13'],
            ['kode' => '203', 'nama' => 'KABUPATEN KLATEN', 'provinsi_kode' => '13'],
            ['kode' => '204', 'nama' => 'KABUPATEN KUDUS', 'provinsi_kode' => '13'],
            ['kode' => '205', 'nama' => 'KABUPATEN MAGELANG', 'provinsi_kode' => '13'],
            ['kode' => '206', 'nama' => 'KABUPATEN PATI', 'provinsi_kode' => '13'],
            ['kode' => '207', 'nama' => 'KABUPATEN PEKALONGAN', 'provinsi_kode' => '13'],
            ['kode' => '208', 'nama' => 'KABUPATEN PEMALANG', 'provinsi_kode' => '13'],
            ['kode' => '209', 'nama' => 'KABUPATEN PURBALINGGA', 'provinsi_kode' => '13'],
            ['kode' => '210', 'nama' => 'KABUPATEN PURWOREJO', 'provinsi_kode' => '13'],
            ['kode' => '211', 'nama' => 'KABUPATEN REMBANG', 'provinsi_kode' => '13'],
            ['kode' => '212', 'nama' => 'KABUPATEN SEMARANG', 'provinsi_kode' => '13'],
            ['kode' => '213', 'nama' => 'KABUPATEN SRAGEN', 'provinsi_kode' => '13'],
            ['kode' => '214', 'nama' => 'KABUPATEN SUKOHARJO', 'provinsi_kode' => '13'],
            ['kode' => '215', 'nama' => 'KABUPATEN TEGAL', 'provinsi_kode' => '13'],
            ['kode' => '216', 'nama' => 'KABUPATEN TEMANGGUNG', 'provinsi_kode' => '13'],
            ['kode' => '217', 'nama' => 'KABUPATEN WONOGIRI', 'provinsi_kode' => '13'],
            ['kode' => '218', 'nama' => 'KABUPATEN WONOSOBO', 'provinsi_kode' => '13'],
            ['kode' => '219', 'nama' => 'KOTA MAGELANG', 'provinsi_kode' => '13'],
            ['kode' => '220', 'nama' => 'KOTA PEKALONGAN', 'provinsi_kode' => '13'],
            ['kode' => '221', 'nama' => 'KOTA SALATIGA', 'provinsi_kode' => '13'],
            ['kode' => '222', 'nama' => 'KOTA SEMARANG', 'provinsi_kode' => '13'],
            ['kode' => '223', 'nama' => 'KOTA SURAKARTA', 'provinsi_kode' => '13'],
            ['kode' => '224', 'nama' => 'KOTA TEGAL', 'provinsi_kode' => '13'],

            // JAWA TIMUR (14)
            ['kode' => '225', 'nama' => 'KABUPATEN BANGKALAN', 'provinsi_kode' => '14'],
            ['kode' => '226', 'nama' => 'KABUPATEN BANYUWANGI', 'provinsi_kode' => '14'],
            ['kode' => '227', 'nama' => 'KABUPATEN BLITAR', 'provinsi_kode' => '14'],
            ['kode' => '228', 'nama' => 'KABUPATEN BOJONEGORO', 'provinsi_kode' => '14'],
            ['kode' => '229', 'nama' => 'KABUPATEN BONDOWOSO', 'provinsi_kode' => '14'],
            ['kode' => '230', 'nama' => 'KABUPATEN GRESIK', 'provinsi_kode' => '14'],
            ['kode' => '231', 'nama' => 'KABUPATEN JEMBER', 'provinsi_kode' => '14'],
            ['kode' => '232', 'nama' => 'KABUPATEN JOMBANG', 'provinsi_kode' => '14'],
            ['kode' => '233', 'nama' => 'KABUPATEN KEDIRI', 'provinsi_kode' => '14'],
            ['kode' => '234', 'nama' => 'KABUPATEN LAMONGAN', 'provinsi_kode' => '14'],
            ['kode' => '235', 'nama' => 'KABUPATEN LUMAJANG', 'provinsi_kode' => '14'],
            ['kode' => '236', 'nama' => 'KABUPATEN MADIUN', 'provinsi_kode' => '14'],
            ['kode' => '237', 'nama' => 'KABUPATEN MAGETAN', 'provinsi_kode' => '14'],
            ['kode' => '238', 'nama' => 'KABUPATEN MALANG', 'provinsi_kode' => '14'],
            ['kode' => '239', 'nama' => 'KABUPATEN MOJOKERTO', 'provinsi_kode' => '14'],
            ['kode' => '240', 'nama' => 'KABUPATEN NGANJUK', 'provinsi_kode' => '14'],
            ['kode' => '241', 'nama' => 'KABUPATEN NGAWI', 'provinsi_kode' => '14'],
            ['kode' => '242', 'nama' => 'KABUPATEN PACITAN', 'provinsi_kode' => '14'],
            ['kode' => '243', 'nama' => 'KABUPATEN PAMEKASAN', 'provinsi_kode' => '14'],
            ['kode' => '244', 'nama' => 'KABUPATEN PASURUAN', 'provinsi_kode' => '14'],
            ['kode' => '245', 'nama' => 'KABUPATEN PONOROGO', 'provinsi_kode' => '14'],
            ['kode' => '246', 'nama' => 'KABUPATEN PROBOLINGGO', 'provinsi_kode' => '14'],
            ['kode' => '247', 'nama' => 'KABUPATEN SAMPANG', 'provinsi_kode' => '14'],
            ['kode' => '248', 'nama' => 'KABUPATEN SIDOARJO', 'provinsi_kode' => '14'],
            ['kode' => '249', 'nama' => 'KABUPATEN SITUBONDO', 'provinsi_kode' => '14'],
            ['kode' => '250', 'nama' => 'KABUPATEN SUMENEP', 'provinsi_kode' => '14'],
            ['kode' => '251', 'nama' => 'KABUPATEN TRENGGALEK', 'provinsi_kode' => '14'],
            ['kode' => '252', 'nama' => 'KABUPATEN TUBAN', 'provinsi_kode' => '14'],
            ['kode' => '253', 'nama' => 'KABUPATEN TULUNGAGUNG', 'provinsi_kode' => '14'],
            ['kode' => '254', 'nama' => 'KOTA BATU', 'provinsi_kode' => '14'],
            ['kode' => '255', 'nama' => 'KOTA BLITAR', 'provinsi_kode' => '14'],
            ['kode' => '256', 'nama' => 'KOTA KEDIRI', 'provinsi_kode' => '14'],
            ['kode' => '257', 'nama' => 'KOTA MADIUN', 'provinsi_kode' => '14'],
            ['kode' => '258', 'nama' => 'KOTA MALANG', 'provinsi_kode' => '14'],
            ['kode' => '259', 'nama' => 'KOTA MOJOKERTO', 'provinsi_kode' => '14'],
            ['kode' => '260', 'nama' => 'KOTA PASURUAN', 'provinsi_kode' => '14'],
            ['kode' => '261', 'nama' => 'KOTA PROBOLINGGO', 'provinsi_kode' => '14'],
            ['kode' => '262', 'nama' => 'KOTA SURABAYA', 'provinsi_kode' => '14'],

            // DKI JAKARTA (15)
            ['kode' => '263', 'nama' => 'KOTA JAKARTA BARAT', 'provinsi_kode' => '15'],
            ['kode' => '264', 'nama' => 'KOTA JAKARTA PUSAT', 'provinsi_kode' => '15'],
            ['kode' => '265', 'nama' => 'KOTA JAKARTA SELATAN', 'provinsi_kode' => '15'],
            ['kode' => '266', 'nama' => 'KOTA JAKARTA TIMUR', 'provinsi_kode' => '15'],
            ['kode' => '267', 'nama' => 'KOTA JAKARTA UTARA', 'provinsi_kode' => '15'],
            ['kode' => '268', 'nama' => 'KABUPATEN KEPULAUAN SERIBU', 'provinsi_kode' => '15'],

            // DAERAH ISTIMEWA YOGYAKARTA (16)
            ['kode' => '269', 'nama' => 'KABUPATEN BANTUL', 'provinsi_kode' => '16'],
            ['kode' => '270', 'nama' => 'KABUPATEN GUNUNGKIDUL', 'provinsi_kode' => '16'],
            ['kode' => '271', 'nama' => 'KABUPATEN KULON PROGO', 'provinsi_kode' => '16'],
            ['kode' => '272', 'nama' => 'KABUPATEN SLEMAN', 'provinsi_kode' => '16'],
            ['kode' => '273', 'nama' => 'KOTA YOGYAKARTA', 'provinsi_kode' => '16'],

            // BALI (17)
            ['kode' => '274', 'nama' => 'KABUPATEN BADUNG', 'provinsi_kode' => '17'],
            ['kode' => '275', 'nama' => 'KABUPATEN BANGLI', 'provinsi_kode' => '17'],
            ['kode' => '276', 'nama' => 'KABUPATEN BULELENG', 'provinsi_kode' => '17'],
            ['kode' => '277', 'nama' => 'KABUPATEN GIANYAR', 'provinsi_kode' => '17'],
            ['kode' => '278', 'nama' => 'KABUPATEN JEMBRANA', 'provinsi_kode' => '17'],
            ['kode' => '279', 'nama' => 'KABUPATEN KARANGASEM', 'provinsi_kode' => '17'],
            ['kode' => '280', 'nama' => 'KABUPATEN KLUNGKUNG', 'provinsi_kode' => '17'],
            ['kode' => '281', 'nama' => 'KABUPATEN TABANAN', 'provinsi_kode' => '17'],
            ['kode' => '282', 'nama' => 'KOTA DENPASAR', 'provinsi_kode' => '17'],

            // NUSA TENGGARA BARAT (18)
            ['kode' => '283', 'nama' => 'KABUPATEN BIMA', 'provinsi_kode' => '18'],
            ['kode' => '284', 'nama' => 'KABUPATEN DOMPU', 'provinsi_kode' => '18'],
            ['kode' => '285', 'nama' => 'KABUPATEN LOMBOK BARAT', 'provinsi_kode' => '18'],
            ['kode' => '286', 'nama' => 'KABUPATEN LOMBOK TENGAH', 'provinsi_kode' => '18'],
            ['kode' => '287', 'nama' => 'KABUPATEN LOMBOK TIMUR', 'provinsi_kode' => '18'],
            ['kode' => '288', 'nama' => 'KABUPATEN LOMBOK UTARA', 'provinsi_kode' => '18'],
            ['kode' => '289', 'nama' => 'KABUPATEN SUMBAWA', 'provinsi_kode' => '18'],
            ['kode' => '290', 'nama' => 'KABUPATEN SUMBAWA BARAT', 'provinsi_kode' => '18'],
            ['kode' => '291', 'nama' => 'KOTA BIMA', 'provinsi_kode' => '18'],
            ['kode' => '292', 'nama' => 'KOTA MATARAM', 'provinsi_kode' => '18'],

            // NUSA TENGGARA TIMUR (19)
            ['kode' => '293', 'nama' => 'KABUPATEN ALOR', 'provinsi_kode' => '19'],
            ['kode' => '294', 'nama' => 'KABUPATEN BELU', 'provinsi_kode' => '19'],
            ['kode' => '295', 'nama' => 'KABUPATEN ENDE', 'provinsi_kode' => '19'],
            ['kode' => '296', 'nama' => 'KABUPATEN FLORES TIMUR', 'provinsi_kode' => '19'],
            ['kode' => '297', 'nama' => 'KABUPATEN KUPANG', 'provinsi_kode' => '19'],
            ['kode' => '298', 'nama' => 'KABUPATEN LEMBATA', 'provinsi_kode' => '19'],
            ['kode' => '299', 'nama' => 'KABUPATEN MALAKA', 'provinsi_kode' => '19'],
            ['kode' => '300', 'nama' => 'KABUPATEN MANGGARAI', 'provinsi_kode' => '19'],
            ['kode' => '301', 'nama' => 'KABUPATEN MANGGARAI BARAT', 'provinsi_kode' => '19'],
            ['kode' => '302', 'nama' => 'KABUPATEN MANGGARAI TIMUR', 'provinsi_kode' => '19'],
            ['kode' => '303', 'nama' => 'KABUPATEN NGADA', 'provinsi_kode' => '19'],
            ['kode' => '304', 'nama' => 'KABUPATEN NAGEKEO', 'provinsi_kode' => '19'],
            ['kode' => '305', 'nama' => 'KABUPATEN ROTE NDAO', 'provinsi_kode' => '19'],
            ['kode' => '306', 'nama' => 'KABUPATEN SABU RAIJUA', 'provinsi_kode' => '19'],
            ['kode' => '307', 'nama' => 'KABUPATEN SIKKA', 'provinsi_kode' => '19'],
            ['kode' => '308', 'nama' => 'KABUPATEN SUMBA BARAT', 'provinsi_kode' => '19'],
            ['kode' => '309', 'nama' => 'KABUPATEN SUMBA BARAT DAYA', 'provinsi_kode' => '19'],
            ['kode' => '310', 'nama' => 'KABUPATEN SUMBA TENGAH', 'provinsi_kode' => '19'],
            ['kode' => '311', 'nama' => 'KABUPATEN SUMBA TIMUR', 'provinsi_kode' => '19'],
            ['kode' => '312', 'nama' => 'KABUPATEN TIMOR TENGAH SELATAN', 'provinsi_kode' => '19'],
            ['kode' => '313', 'nama' => 'KABUPATEN TIMOR TENGAH UTARA', 'provinsi_kode' => '19'],
            ['kode' => '314', 'nama' => 'KOTA KUPANG', 'provinsi_kode' => '19'],

            // KALIMANTAN BARAT (20)
            ['kode' => '315', 'nama' => 'KABUPATEN BENGKAYANG', 'provinsi_kode' => '20'],
            ['kode' => '316', 'nama' => 'KABUPATEN KAPUAS HULU', 'provinsi_kode' => '20'],
            ['kode' => '317', 'nama' => 'KABUPATEN KAYONG UTARA', 'provinsi_kode' => '20'],
            ['kode' => '318', 'nama' => 'KABUPATEN KETAPANG', 'provinsi_kode' => '20'],
            ['kode' => '319', 'nama' => 'KABUPATEN KUBU RAYA', 'provinsi_kode' => '20'],
            ['kode' => '320', 'nama' => 'KABUPATEN LANDAK', 'provinsi_kode' => '20'],
            ['kode' => '321', 'nama' => 'KABUPATEN MELAWI', 'provinsi_kode' => '20'],
            ['kode' => '322', 'nama' => 'KABUPATEN MEMPAWAH', 'provinsi_kode' => '20'],
            ['kode' => '323', 'nama' => 'KABUPATEN SAMBAS', 'provinsi_kode' => '20'],
            ['kode' => '324', 'nama' => 'KABUPATEN SANGGAU', 'provinsi_kode' => '20'],
            ['kode' => '325', 'nama' => 'KABUPATEN SEKADAU', 'provinsi_kode' => '20'],
            ['kode' => '326', 'nama' => 'KABUPATEN SINTANG', 'provinsi_kode' => '20'],
            ['kode' => '327', 'nama' => 'KOTA PONTIANAK', 'provinsi_kode' => '20'],
            ['kode' => '328', 'nama' => 'KOTA SINGKAWANG', 'provinsi_kode' => '20'],

            // KALIMANTAN SELATAN (21)
            ['kode' => '329', 'nama' => 'KABUPATEN BALANGAN', 'provinsi_kode' => '21'],
            ['kode' => '330', 'nama' => 'KABUPATEN BANJAR', 'provinsi_kode' => '21'],
            ['kode' => '331', 'nama' => 'KABUPATEN BARITO KUALA', 'provinsi_kode' => '21'],
            ['kode' => '332', 'nama' => 'KABUPATEN HULU SUNGAI SELATAN', 'provinsi_kode' => '21'],
            ['kode' => '333', 'nama' => 'KABUPATEN HULU SUNGAI TENGAH', 'provinsi_kode' => '21'],
            ['kode' => '334', 'nama' => 'KABUPATEN HULU SUNGAI UTARA', 'provinsi_kode' => '21'],
            ['kode' => '335', 'nama' => 'KABUPATEN KOTABARU', 'provinsi_kode' => '21'],
            ['kode' => '336', 'nama' => 'KABUPATEN TABALONG', 'provinsi_kode' => '21'],
            ['kode' => '337', 'nama' => 'KABUPATEN TANAH BUMBU', 'provinsi_kode' => '21'],
            ['kode' => '338', 'nama' => 'KABUPATEN TANAH LAUT', 'provinsi_kode' => '21'],
            ['kode' => '339', 'nama' => 'KABUPATEN TAPIN', 'provinsi_kode' => '21'],
            ['kode' => '340', 'nama' => 'KOTA BANJARBARU', 'provinsi_kode' => '21'],
            ['kode' => '341', 'nama' => 'KOTA BANJARMASIN', 'provinsi_kode' => '21'],

            // KALIMANTAN TENGAH (22)
            ['kode' => '342', 'nama' => 'KABUPATEN BARITO SELATAN', 'provinsi_kode' => '22'],
            ['kode' => '343', 'nama' => 'KABUPATEN BARITO TIMUR', 'provinsi_kode' => '22'],
            ['kode' => '344', 'nama' => 'KABUPATEN BARITO UTARA', 'provinsi_kode' => '22'],
            ['kode' => '345', 'nama' => 'KABUPATEN GUNUNG MAS', 'provinsi_kode' => '22'],
            ['kode' => '346', 'nama' => 'KABUPATEN KAPUAS', 'provinsi_kode' => '22'],
            ['kode' => '347', 'nama' => 'KABUPATEN KATINGAN', 'provinsi_kode' => '22'],
            ['kode' => '348', 'nama' => 'KABUPATEN KOTAWARINGIN BARAT', 'provinsi_kode' => '22'],
            ['kode' => '349', 'nama' => 'KABUPATEN KOTAWARINGIN TIMUR', 'provinsi_kode' => '22'],
            ['kode' => '350', 'nama' => 'KABUPATEN LAMANDAU', 'provinsi_kode' => '22'],
            ['kode' => '351', 'nama' => 'KABUPATEN MURUNG RAYA', 'provinsi_kode' => '22'],
            ['kode' => '352', 'nama' => 'KABUPATEN PULANG PISAU', 'provinsi_kode' => '22'],
            ['kode' => '353', 'nama' => 'KABUPATEN SUKAMARA', 'provinsi_kode' => '22'],
            ['kode' => '354', 'nama' => 'KABUPATEN SERUYAN', 'provinsi_kode' => '22'],
            ['kode' => '355', 'nama' => 'KOTA PALANGKA RAYA', 'provinsi_kode' => '22'],

            // KALIMANTAN TIMUR (23)
            ['kode' => '356', 'nama' => 'KABUPATEN BERAU', 'provinsi_kode' => '23'],
            ['kode' => '357', 'nama' => 'KABUPATEN KUTAI BARAT', 'provinsi_kode' => '23'],
            ['kode' => '358', 'nama' => 'KABUPATEN KUTAI KARTANEGARA', 'provinsi_kode' => '23'],
            ['kode' => '359', 'nama' => 'KABUPATEN KUTAI TIMUR', 'provinsi_kode' => '23'],
            ['kode' => '360', 'nama' => 'KABUPATEN MAHAKAM ULU', 'provinsi_kode' => '23'],
            ['kode' => '361', 'nama' => 'KABUPATEN PASER', 'provinsi_kode' => '23'],
            ['kode' => '362', 'nama' => 'KABUPATEN PENAJAM PASER UTARA', 'provinsi_kode' => '23'],
            ['kode' => '363', 'nama' => 'KOTA BALIKPAPAN', 'provinsi_kode' => '23'],
            ['kode' => '364', 'nama' => 'KOTA BONTANG', 'provinsi_kode' => '23'],
            ['kode' => '365', 'nama' => 'KOTA SAMARINDA', 'provinsi_kode' => '23'],

            // KALIMANTAN UTARA (24)
            ['kode' => '366', 'nama' => 'KABUPATEN BULUNGAN', 'provinsi_kode' => '24'],
            ['kode' => '367', 'nama' => 'KABUPATEN MALINAU', 'provinsi_kode' => '24'],
            ['kode' => '368', 'nama' => 'KABUPATEN NUNUKAN', 'provinsi_kode' => '24'],
            ['kode' => '369', 'nama' => 'KABUPATEN TANA TIDUNG', 'provinsi_kode' => '24'],
            ['kode' => '370', 'nama' => 'KOTA TARAKAN', 'provinsi_kode' => '24'],

            // GORONTALO (25)
            ['kode' => '371', 'nama' => 'KABUPATEN BOALEMO', 'provinsi_kode' => '25'],
            ['kode' => '372', 'nama' => 'KABUPATEN BONE BOLANGO', 'provinsi_kode' => '25'],
            ['kode' => '373', 'nama' => 'KABUPATEN GORONTALO', 'provinsi_kode' => '25'],
            ['kode' => '374', 'nama' => 'KABUPATEN GORONTALO UTARA', 'provinsi_kode' => '25'],
            ['kode' => '375', 'nama' => 'KABUPATEN POHUWATO', 'provinsi_kode' => '25'],
            ['kode' => '376', 'nama' => 'KOTA GORONTALO', 'provinsi_kode' => '25'],

            // SULAWESI SELATAN (26)
            ['kode' => '377', 'nama' => 'KABUPATEN BANTAENG', 'provinsi_kode' => '26'],
            ['kode' => '378', 'nama' => 'KABUPATEN BARRU', 'provinsi_kode' => '26'],
            ['kode' => '379', 'nama' => 'KABUPATEN BONE', 'provinsi_kode' => '26'],
            ['kode' => '380', 'nama' => 'KABUPATEN BULUKUMBA', 'provinsi_kode' => '26'],
            ['kode' => '381', 'nama' => 'KABUPATEN ENREKANG', 'provinsi_kode' => '26'],
            ['kode' => '382', 'nama' => 'KABUPATEN GOWA', 'provinsi_kode' => '26'],
            ['kode' => '383', 'nama' => 'KABUPATEN JENEPONTO', 'provinsi_kode' => '26'],
            ['kode' => '384', 'nama' => 'KABUPATEN KEPULAUAN SELAYAR', 'provinsi_kode' => '26'],
            ['kode' => '385', 'nama' => 'KABUPATEN LUWU', 'provinsi_kode' => '26'],
            ['kode' => '386', 'nama' => 'KABUPATEN LUWU TIMUR', 'provinsi_kode' => '26'],
            ['kode' => '387', 'nama' => 'KABUPATEN LUWU UTARA', 'provinsi_kode' => '26'],
            ['kode' => '388', 'nama' => 'KABUPATEN MAROS', 'provinsi_kode' => '26'],
            ['kode' => '389', 'nama' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'provinsi_kode' => '26'],
            ['kode' => '390', 'nama' => 'KABUPATEN PINRANG', 'provinsi_kode' => '26'],
            ['kode' => '391', 'nama' => 'KABUPATEN SIDENRENG RAPPANG', 'provinsi_kode' => '26'],
            ['kode' => '392', 'nama' => 'KABUPATEN SINJAI', 'provinsi_kode' => '26'],
            ['kode' => '393', 'nama' => 'KABUPATEN SOPPENG', 'provinsi_kode' => '26'],
            ['kode' => '394', 'nama' => 'KABUPATEN TAKALAR', 'provinsi_kode' => '26'],
            ['kode' => '395', 'nama' => 'KABUPATEN TANA TORAJA', 'provinsi_kode' => '26'],
            ['kode' => '396', 'nama' => 'KABUPATEN TORAJA UTARA', 'provinsi_kode' => '26'],
            ['kode' => '397', 'nama' => 'KABUPATEN WAJO', 'provinsi_kode' => '26'],
            ['kode' => '398', 'nama' => 'KOTA MAKASSAR', 'provinsi_kode' => '26'],
            ['kode' => '399', 'nama' => 'KOTA PALOPO', 'provinsi_kode' => '26'],
            ['kode' => '400', 'nama' => 'KOTA PAREPARE', 'provinsi_kode' => '26'],

            // SULAWESI TENGGARA (27)
            ['kode' => '401', 'nama' => 'KABUPATEN BOMBANA', 'provinsi_kode' => '27'],
            ['kode' => '402', 'nama' => 'KABUPATEN BUTON', 'provinsi_kode' => '27'],
            ['kode' => '403', 'nama' => 'KABUPATEN BUTON SELATAN', 'provinsi_kode' => '27'],
            ['kode' => '404', 'nama' => 'KABUPATEN BUTON TENGAH', 'provinsi_kode' => '27'],
            ['kode' => '405', 'nama' => 'KABUPATEN BUTON UTARA', 'provinsi_kode' => '27'],
            ['kode' => '406', 'nama' => 'KABUPATEN KOLAKA', 'provinsi_kode' => '27'],
            ['kode' => '407', 'nama' => 'KABUPATEN KOLAKA TIMUR', 'provinsi_kode' => '27'],
            ['kode' => '408', 'nama' => 'KABUPATEN KOLAKA UTARA', 'provinsi_kode' => '27'],
            ['kode' => '409', 'nama' => 'KABUPATEN KONAWE', 'provinsi_kode' => '27'],
            ['kode' => '410', 'nama' => 'KABUPATEN KONAWE KEPULAUAN', 'provinsi_kode' => '27'],
            ['kode' => '411', 'nama' => 'KABUPATEN KONAWE SELATAN', 'provinsi_kode' => '27'],
            ['kode' => '412', 'nama' => 'KABUPATEN KONAWE UTARA', 'provinsi_kode' => '27'],
            ['kode' => '413', 'nama' => 'KABUPATEN MUNA', 'provinsi_kode' => '27'],
            ['kode' => '414', 'nama' => 'KABUPATEN MUNA BARAT', 'provinsi_kode' => '27'],
            ['kode' => '415', 'nama' => 'KABUPATEN WAKATOBI', 'provinsi_kode' => '27'],
            ['kode' => '416', 'nama' => 'KOTA BAU-BAU', 'provinsi_kode' => '27'],
            ['kode' => '417', 'nama' => 'KOTA KENDARI', 'provinsi_kode' => '27'],

            // SULAWESI TENGAH (28)
            ['kode' => '418', 'nama' => 'KABUPATEN BANGGAI', 'provinsi_kode' => '28'],
            ['kode' => '419', 'nama' => 'KABUPATEN BANGGAI KEPULAUAN', 'provinsi_kode' => '28'],
            ['kode' => '420', 'nama' => 'KABUPATEN BANGGAI LAUT', 'provinsi_kode' => '28'],
            ['kode' => '421', 'nama' => 'KABUPATEN BUOL', 'provinsi_kode' => '28'],
            ['kode' => '422', 'nama' => 'KABUPATEN DONGGALA', 'provinsi_kode' => '28'],
            ['kode' => '423', 'nama' => 'KABUPATEN MOROWALI', 'provinsi_kode' => '28'],
            ['kode' => '424', 'nama' => 'KABUPATEN MOROWALI UTARA', 'provinsi_kode' => '28'],
            ['kode' => '425', 'nama' => 'KABUPATEN PARIGI MOUTONG', 'provinsi_kode' => '28'],
            ['kode' => '426', 'nama' => 'KABUPATEN POSO', 'provinsi_kode' => '28'],
            ['kode' => '427', 'nama' => 'KABUPATEN SIGI', 'provinsi_kode' => '28'],
            ['kode' => '428', 'nama' => 'KABUPATEN TOJO UNA-UNA', 'provinsi_kode' => '28'],
            ['kode' => '429', 'nama' => 'KABUPATEN TOLI-TOLI', 'provinsi_kode' => '28'],
            ['kode' => '430', 'nama' => 'KOTA PALU', 'provinsi_kode' => '28'],

            // SULAWESI UTARA (29)
            ['kode' => '431', 'nama' => 'KABUPATEN BOLAANG MONGONDOW', 'provinsi_kode' => '29'],
            ['kode' => '432', 'nama' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'provinsi_kode' => '29'],
            ['kode' => '433', 'nama' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'provinsi_kode' => '29'],
            ['kode' => '434', 'nama' => 'KABUPATEN BOLAANG MONGONDOW UTARA', 'provinsi_kode' => '29'],
            ['kode' => '435', 'nama' => 'KABUPATEN KEPULAUAN SANGIHE', 'provinsi_kode' => '29'],
            ['kode' => '436', 'nama' => 'KABUPATEN KEPULAUAN SIAU TAGULANDANG BIARO', 'provinsi_kode' => '29'],
            ['kode' => '437', 'nama' => 'KABUPATEN KEPULAUAN TALAUD', 'provinsi_kode' => '29'],
            ['kode' => '438', 'nama' => 'KABUPATEN MINAHASA', 'provinsi_kode' => '29'],
            ['kode' => '439', 'nama' => 'KABUPATEN MINAHASA SELATAN', 'provinsi_kode' => '29'],
            ['kode' => '440', 'nama' => 'KABUPATEN MINAHASA TENGGARA', 'provinsi_kode' => '29'],
            ['kode' => '441', 'nama' => 'KABUPATEN MINAHASA UTARA', 'provinsi_kode' => '29'],
            ['kode' => '442', 'nama' => 'KOTA BITUNG', 'provinsi_kode' => '29'],
            ['kode' => '443', 'nama' => 'KOTA KOTAMOBAGU', 'provinsi_kode' => '29'],
            ['kode' => '444', 'nama' => 'KOTA MANADO', 'provinsi_kode' => '29'],
            ['kode' => '445', 'nama' => 'KOTA TOMOHON', 'provinsi_kode' => '29'],

            // SULAWESI BARAT (30)
            ['kode' => '446', 'nama' => 'KABUPATEN MAJENE', 'provinsi_kode' => '30'],
            ['kode' => '447', 'nama' => 'KABUPATEN MAMASA', 'provinsi_kode' => '30'],
            ['kode' => '448', 'nama' => 'KABUPATEN MAMUJU', 'provinsi_kode' => '30'],
            ['kode' => '449', 'nama' => 'KABUPATEN MAMUJU TENGAH', 'provinsi_kode' => '30'],
            ['kode' => '450', 'nama' => 'KABUPATEN MAMUJU UTARA', 'provinsi_kode' => '30'],
            ['kode' => '451', 'nama' => 'KABUPATEN POLEWALI MANDAR', 'provinsi_kode' => '30'],
            ['kode' => '452', 'nama' => 'KOTA MAMUJU', 'provinsi_kode' => '30'],

            // MALUKU (31)
            ['kode' => '453', 'nama' => 'KABUPATEN BURU', 'provinsi_kode' => '31'],
            ['kode' => '454', 'nama' => 'KABUPATEN BURU SELATAN', 'provinsi_kode' => '31'],
            ['kode' => '455', 'nama' => 'KABUPATEN KEPULAUAN ARU', 'provinsi_kode' => '31'],
            ['kode' => '456', 'nama' => 'KABUPATEN MALUKU BARAT DAYA', 'provinsi_kode' => '31'],
            ['kode' => '457', 'nama' => 'KABUPATEN MALUKU TENGAH', 'provinsi_kode' => '31'],
            ['kode' => '458', 'nama' => 'KABUPATEN MALUKU TENGGARA', 'provinsi_kode' => '31'],
            ['kode' => '459', 'nama' => 'KABUPATEN MALUKU TENGGARA BARAT', 'provinsi_kode' => '31'],
            ['kode' => '460', 'nama' => 'KABUPATEN SERAM BAGIAN BARAT', 'provinsi_kode' => '31'],
            ['kode' => '461', 'nama' => 'KABUPATEN SERAM BAGIAN TIMUR', 'provinsi_kode' => '31'],
            ['kode' => '462', 'nama' => 'KOTA AMBON', 'provinsi_kode' => '31'],
            ['kode' => '463', 'nama' => 'KOTA TUAL', 'provinsi_kode' => '31'],

            // MALUKU UTARA (32)
            ['kode' => '464', 'nama' => 'KABUPATEN HALMAHERA BARAT', 'provinsi_kode' => '32'],
            ['kode' => '465', 'nama' => 'KABUPATEN HALMAHERA TENGAH', 'provinsi_kode' => '32'],
            ['kode' => '466', 'nama' => 'KABUPATEN HALMAHERA UTARA', 'provinsi_kode' => '32'],
            ['kode' => '467', 'nama' => 'KABUPATEN HALMAHERA SELATAN', 'provinsi_kode' => '32'],
            ['kode' => '468', 'nama' => 'KABUPATEN KEPULAUAN SULA', 'provinsi_kode' => '32'],
            ['kode' => '469', 'nama' => 'KABUPATEN HALMAHERA TIMUR', 'provinsi_kode' => '32'],
            ['kode' => '470', 'nama' => 'KABUPATEN PULAU MOROTAI', 'provinsi_kode' => '32'],
            ['kode' => '471', 'nama' => 'KABUPATEN PULAU TALIABU', 'provinsi_kode' => '32'],
            ['kode' => '472', 'nama' => 'KOTA TERNATE', 'provinsi_kode' => '32'],
            ['kode' => '473', 'nama' => 'KOTA TIDORE KEPULAUAN', 'provinsi_kode' => '32'],

            // PAPUA (33)
            ['kode' => '474', 'nama' => 'KABUPATEN ASMAT', 'provinsi_kode' => '33'],
            ['kode' => '475', 'nama' => 'KABUPATEN BIAK NUMFOR', 'provinsi_kode' => '33'],
            ['kode' => '476', 'nama' => 'KABUPATEN BOVEN DIGOEL', 'provinsi_kode' => '33'],
            ['kode' => '477', 'nama' => 'KABUPATEN DEIYAI', 'provinsi_kode' => '33'],
            ['kode' => '478', 'nama' => 'KABUPATEN DOGIYAI', 'provinsi_kode' => '33'],
            ['kode' => '479', 'nama' => 'KABUPATEN INTAN JAYA', 'provinsi_kode' => '33'],
            ['kode' => '480', 'nama' => 'KABUPATEN JAYAPURA', 'provinsi_kode' => '33'],
            ['kode' => '481', 'nama' => 'KABUPATEN JAYAWIJAYA', 'provinsi_kode' => '33'],
            ['kode' => '482', 'nama' => 'KABUPATEN KEEROM', 'provinsi_kode' => '33'],
            ['kode' => '483', 'nama' => 'KABUPATEN KEPULAUAN YAPEN', 'provinsi_kode' => '33'],
            ['kode' => '484', 'nama' => 'KABUPATEN LANNY JAYA', 'provinsi_kode' => '33'],
            ['kode' => '485', 'nama' => 'KABUPATEN MAMBERAMO RAYA', 'provinsi_kode' => '33'],
            ['kode' => '486', 'nama' => 'KABUPATEN MAMBERAMO TENGAH', 'provinsi_kode' => '33'],
            ['kode' => '487', 'nama' => 'KABUPATEN MAPPI', 'provinsi_kode' => '33'],
            ['kode' => '488', 'nama' => 'KABUPATEN MERAUKE', 'provinsi_kode' => '33'],
            ['kode' => '489', 'nama' => 'KABUPATEN MIMIKA', 'provinsi_kode' => '33'],
            ['kode' => '490', 'nama' => 'KABUPATEN NABIRE', 'provinsi_kode' => '33'],
            ['kode' => '491', 'nama' => 'KABUPATEN NDUGA', 'provinsi_kode' => '33'],
            ['kode' => '492', 'nama' => 'KABUPATEN PANIAI', 'provinsi_kode' => '33'],
            ['kode' => '493', 'nama' => 'KABUPATEN PEGUNUNGAN BINTANG', 'provinsi_kode' => '33'],
            ['kode' => '494', 'nama' => 'KABUPATEN PUNCAK', 'provinsi_kode' => '33'],
            ['kode' => '495', 'nama' => 'KABUPATEN PUNCAK JAYA', 'provinsi_kode' => '33'],
            ['kode' => '496', 'nama' => 'KABUPATEN SARMI', 'provinsi_kode' => '33'],
            ['kode' => '497', 'nama' => 'KABUPATEN SUPIORI', 'provinsi_kode' => '33'],
            ['kode' => '498', 'nama' => 'KABUPATEN TOLIKARA', 'provinsi_kode' => '33'],
            ['kode' => '499', 'nama' => 'KABUPATEN WAROPEN', 'provinsi_kode' => '33'],
            ['kode' => '500', 'nama' => 'KABUPATEN YAHUKIMO', 'provinsi_kode' => '33'],
            ['kode' => '501', 'nama' => 'KABUPATEN YALIMO', 'provinsi_kode' => '33'],
            ['kode' => '502', 'nama' => 'KOTA JAYAPURA', 'provinsi_kode' => '33'],

            // PAPUA BARAT (34)
            ['kode' => '503', 'nama' => 'KABUPATEN FAKFAK', 'provinsi_kode' => '34'],
            ['kode' => '504', 'nama' => 'KABUPATEN KAIMANA', 'provinsi_kode' => '34'],
            ['kode' => '505', 'nama' => 'KABUPATEN MANOKWARI', 'provinsi_kode' => '34'],
            ['kode' => '506', 'nama' => 'KABUPATEN MANOKWARI SELATAN', 'provinsi_kode' => '34'],
            ['kode' => '507', 'nama' => 'KABUPATEN MAYBRAT', 'provinsi_kode' => '34'],
            ['kode' => '508', 'nama' => 'KABUPATEN PEGUNUNGAN ARFAK', 'provinsi_kode' => '34'],
            ['kode' => '509', 'nama' => 'KABUPATEN RAJA AMPAT', 'provinsi_kode' => '34'],
            ['kode' => '510', 'nama' => 'KABUPATEN SORONG', 'provinsi_kode' => '34'],
            ['kode' => '511', 'nama' => 'KABUPATEN SORONG SELATAN', 'provinsi_kode' => '34'],
            ['kode' => '512', 'nama' => 'KABUPATEN TAMBRAUW', 'provinsi_kode' => '34'],
            ['kode' => '513', 'nama' => 'KABUPATEN TELUK BINTUNI', 'provinsi_kode' => '34'],
            ['kode' => '514', 'nama' => 'KABUPATEN TELUK WONDAMA', 'provinsi_kode' => '34'],

            // LAIN-LAIN (35)
            ['kode' => '515', 'nama' => 'LAIN-LAIN', 'provinsi_kode' => '35'],

        ];

        foreach ($kabupaten as $data) {
            Kabupaten::create($data);
        }
    }
}
